apiVersion: v1
kind: Secret
metadata:
  name: private-github-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/user/repo
  password: personal_access_token
  username: not-used
